// Code generated by benc generator; DO NOT EDIT.
package server

import (
	bstd "github.com/banditmoscow1337/benc/std/golang"
)

func (serverIdentity *ServerIdentity) Size() (s int) {
	s += bstd.SizeString(serverIdentity.PrivateKeyPEM)
	s += bstd.SizeString(serverIdentity.PublicKeyPEM)
	s += bstd.SizeString(serverIdentity.EncPrivateKeyPEM)
	s += bstd.SizeString(serverIdentity.EncPublicKeyPEM)
	s += bstd.SizeSlice(serverIdentity.MerkleLeaves, func(v []byte) int { return bstd.SizeBytes(v) })
	return
}

func (serverIdentity *ServerIdentity) Marshal(tn int, b []byte) (n int) {
	n = tn
	n = bstd.MarshalString(n, b, serverIdentity.PrivateKeyPEM)
	n = bstd.MarshalString(n, b, serverIdentity.PublicKeyPEM)
	n = bstd.MarshalString(n, b, serverIdentity.EncPrivateKeyPEM)
	n = bstd.MarshalString(n, b, serverIdentity.EncPublicKeyPEM)
	n = bstd.MarshalSlice(n, b, serverIdentity.MerkleLeaves, func(n int, b []byte, v []byte) int { return bstd.MarshalBytes(n, b, v) })
	return n
}

func (serverIdentity *ServerIdentity) Unmarshal(tn int, b []byte) (n int, err error) {
	n = tn
	if n, serverIdentity.PrivateKeyPEM, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	if n, serverIdentity.PublicKeyPEM, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	if n, serverIdentity.EncPrivateKeyPEM, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	if n, serverIdentity.EncPublicKeyPEM, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	if n, serverIdentity.MerkleLeaves, err = bstd.UnmarshalSlice[[]byte](n, b, func(n int, b []byte, v *[]byte) (int, error) {
		var err error
		n, *v, err = bstd.UnmarshalBytesCopied(n, b)
		return n, err
	}); err != nil {
		serverIdentity.MerkleLeaves = nil
		err = nil
	}
	return
}

func (serverToken *ServerToken) Size() (s int) {
	s += bstd.SizeString(serverToken.Addr)
	s += bstd.SizeString(serverToken.PEM)
	s += bstd.SizeString(serverToken.EncPEM)
	return
}

func (serverToken *ServerToken) Marshal(tn int, b []byte) (n int) {
	n = tn
	n = bstd.MarshalString(n, b, serverToken.Addr)
	n = bstd.MarshalString(n, b, serverToken.PEM)
	n = bstd.MarshalString(n, b, serverToken.EncPEM)
	return n
}

func (serverToken *ServerToken) Unmarshal(tn int, b []byte) (n int, err error) {
	n = tn
	if n, serverToken.Addr, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	if n, serverToken.PEM, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	if n, serverToken.EncPEM, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	return
}