// Code generated by benc generator; DO NOT EDIT.

package client

import (
	bstd "github.com/banditmoscow1337/benc/std/golang"
)


func (fileMeta *fileMeta) Sizer() (s int) {
	s += bstd.SizeString(fileMeta.Name)
	s += bstd.SizeInt64()
	s += bstd.SizeString(fileMeta.ID)
	return
}

func (fileMeta *fileMeta) Marshal(tn int, b []byte) (n int) {
	n = tn
	n = bstd.MarshalString(n, b, fileMeta.Name)
	n = bstd.MarshalInt64(n, b, fileMeta.Size)
	n = bstd.MarshalString(n, b, fileMeta.ID)
	return n
}

func (fileMeta *fileMeta) Unmarshal(tn int, b []byte) (n int, err error) {
	n = tn
	if n, fileMeta.Name, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	if n, fileMeta.Size, err = bstd.UnmarshalInt64(n, b); err != nil {
		return
	}
	if n, fileMeta.ID, err = bstd.UnmarshalString(n, b); err != nil {
		return
	}
	return
}
